import Link from 'next/link';

export const metadata = {
    title: 'Terms of Service | Right It Up',
    description: 'Terms of Service for Right It Up - AI-powered dispute resolution platform',
};

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen">
            <main className="pt-28 md:pt-32 px-4 md:px-10 pb-20">
                <div className="max-w-3xl mx-auto">
                    <div className="mb-10">
                        <Link href="/" className="text-electric-violet hover:text-cyber-blue transition-colors text-sm">
                            ← Back to Home
                        </Link>
                    </div>

                    <h1 className="text-4xl md:text-5xl font-black text-starlight-white mb-4">
                        Terms of Service
                    </h1>
                    <p className="text-steel-grey mb-10">
                        Last updated: December 2024
                    </p>

                    <div className="prose prose-invert max-w-none space-y-8">
                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">1. Acceptance of Terms</h2>
                            <p className="text-steel-grey leading-relaxed">
                                By accessing or using Right It Up (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
                                If you disagree with any part of these terms, you may not access the Service.
                                We reserve the right to update these terms at any time, and your continued use constitutes acceptance of any changes.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">2. Description of Service</h2>
                            <p className="text-steel-grey leading-relaxed">
                                Right It Up is an AI-powered platform that facilitates dispute resolution between parties.
                                Users submit their arguments, and our AI system analyzes both sides to generate a verdict.
                                The Service is intended for entertainment and informal dispute resolution purposes only.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">3. Entertainment Purposes Only</h2>
                            <p className="text-steel-grey leading-relaxed">
                                <strong className="text-caution-amber">Important:</strong> All verdicts generated by Right It Up are for entertainment purposes only.
                                Our AI-generated decisions do not constitute legal advice, binding arbitration, or professional mediation.
                                The verdicts have no legal standing and should not be used as the basis for legal action.
                                For serious disputes, please consult qualified legal or mediation professionals.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">4. User Accounts & Authentication</h2>
                            <p className="text-steel-grey leading-relaxed">
                                You must create an account via Google OAuth to use the Service.
                                You are responsible for maintaining the security of your account credentials.
                                Authenticated users receive five verdicts per day.
                                Account sharing or automated access is prohibited.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">5. User Conduct</h2>
                            <p className="text-steel-grey leading-relaxed mb-4">
                                When using the Service, you agree not to:
                            </p>
                            <ul className="list-disc list-inside text-steel-grey space-y-2 ml-4">
                                <li>Submit false, misleading, or fabricated arguments</li>
                                <li>Upload illegal, harmful, or offensive content as evidence</li>
                                <li>Attempt to manipulate or exploit the AI system</li>
                                <li>Harass other users or use the Service for defamation</li>
                                <li>Circumvent rate limits or usage restrictions</li>
                                <li>Use the Service for any unlawful purpose</li>
                                <li>Attempt to reverse engineer or compromise the platform</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">6. Content Ownership & License</h2>
                            <p className="text-steel-grey leading-relaxed">
                                You retain ownership of the content you submit. By using the Service, you grant us a non-exclusive,
                                worldwide license to process, analyze, and store your submissions for the purpose of generating verdicts.
                                AI-generated verdicts are provided for your personal use and may be shared, but remain the intellectual property of Right It Up.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">7. Evidence & Uploads</h2>
                            <p className="text-steel-grey leading-relaxed">
                                Users may upload images and text as supporting evidence. You represent that you have the right to share any content you upload.
                                We reserve the right to remove content that violates these terms or applicable laws.
                                Uploaded evidence is stored securely and associated with your case.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">8. Case Expiration</h2>
                            <p className="text-steel-grey leading-relaxed">
                                Cases awaiting a response expire after 48 hours. Expired cases cannot be reactivated.
                                Completed verdicts remain accessible indefinitely but may be subject to data retention policies.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">9. Limitation of Liability</h2>
                            <p className="text-steel-grey leading-relaxed">
                                The Service is provided &quot;as is&quot; without warranties of any kind.
                                We are not liable for any damages arising from your use of the Service, including but not limited to
                                decisions made based on AI verdicts, relationship impacts, or disputes arising from the results.
                                Our maximum liability is limited to the amount you paid for the Service (if any).
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">10. Indemnification</h2>
                            <p className="text-steel-grey leading-relaxed">
                                You agree to indemnify and hold harmless Right It Up, its operators, and affiliates from any claims,
                                damages, or expenses arising from your use of the Service or violation of these terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">11. Termination</h2>
                            <p className="text-steel-grey leading-relaxed">
                                We reserve the right to suspend or terminate your access to the Service at any time,
                                for any reason, including violation of these terms. Upon termination, your right to use the Service ceases immediately.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">12. Governing Law</h2>
                            <p className="text-steel-grey leading-relaxed">
                                These terms are governed by applicable laws. Any disputes shall be resolved through
                                good-faith negotiation or, if necessary, through appropriate legal channels in the jurisdiction where the Service operates.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-starlight-white mb-4">13. Contact</h2>
                            <p className="text-steel-grey leading-relaxed">
                                For questions about these Terms of Service, please contact us through our platform.
                            </p>
                        </section>
                    </div>

                    <div className="mt-12 pt-8 border-t border-white/10">
                        <Link href="/privacy" className="text-electric-violet hover:text-cyber-blue transition-colors">
                            View Privacy Policy →
                        </Link>
                    </div>
                </div>
            </main>
        </div>
    );
}